version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:jvca1996@db:5432/last-mile
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jvca1996
      - POSTGRES_DB=last-mile
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}